name: Emergency Rollback

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: 'Tag to rollback to (leave empty for previous release)'
        required: false
        type: string
      reason:
        description: 'Reason for rollback'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine rollback target
      id: target
      run: |
        if [ -n "${{ inputs.target_tag }}" ]; then
          echo "tag=${{ inputs.target_tag }}" >> $GITHUB_OUTPUT
        else
          # Get the previous tag
          PREVIOUS_TAG=$(git tag --sort=-version:refname | head -2 | tail -1)
          echo "tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
        fi

    - name: Checkout target version
      run: |
        git checkout ${{ steps.target.outputs.tag }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build rollback version
      run: npm run build
      env:
        NODE_ENV: production

    - name: Create database rollback script
      run: |
        # This would generate SQL to rollback to previous state
        echo "-- Rollback script for ${{ steps.target.outputs.tag }}" > rollback.sql

    - name: Deploy rollback
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'

    - name: Verify rollback
      run: |
        sleep 30
        npm run test:smoke
      env:
        PRODUCTION_URL: https://your-app.vercel.app

    - name: Log incident
      run: |
        curl -X POST "${{ secrets.INCIDENT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "event": "rollback_completed",
            "tag": "${{ steps.target.outputs.tag }}",
            "reason": "${{ inputs.reason }}",
            "timestamp": "'$(date -Iseconds)'"
          }'

    - name: Notify team
      uses: 8398a7/action-slack@v3
      with:
        status: 'custom'
        custom_payload: |
          {
            "text": "🚨 ROLLBACK COMPLETED",
            "attachments": [{
              "color": "warning",
              "fields": [{
                "title": "Target Version",
                "value": "${{ steps.target.outputs.tag }}",
                "short": true
              }, {
                "title": "Reason",
                "value": "${{ inputs.reason }}",
                "short": false
              }]
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}